import { Geist } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const esRebound = localFont({
  variable: "--font-rebound",
  src: [
    {
      path: "../../fonts/esrebound/Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/BoldItalic.otf",
      weight: "700",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/extraBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/extraBoldItalic.otf",
      weight: "800",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/Italic.otf",
      weight: "400",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/LightItalic.otf",
      weight: "300",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/ThinItalic.otf",
      weight: "100",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/SemiBoldItalic.otf",
      weight: "600",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/extraLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/extraLightItalic.otf",
      weight: "200",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/MediumItalic.otf",
      weight: "500",
      style: "Italic",
    },
    {
      path: "../../fonts/esrebound/Hairline.otf",
      weight: "50",
      style: "normal",
    },
    {
      path: "../../fonts/esrebound/HairlineItalic.otf",
      weight: "50",
      style: "Italic",
    }
  ]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,200" />
      </head>
      <body
        className={`${geistSans.variable} ${esRebound.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}